### ISSUE TITLE
how to config multiple buckets

### ISSUE THREAD

**Issue by ivanmissu** [beeyev/thumbor-s3-docker#1]
i have 3 buckets in minio,  how to config in thumbor??

**Comment by beeyev** [comment]
Have you checked this example?
https://github.com/beeyev/thumbor-s3-docker/blob/master/examples/read-from-S3-cache-to-S3/docker-compose.yml

Also take a look at this repo https://github.com/thumbor/thumbor-aws
It explains how to use S3, since this module is used in the docker image.
