### ISSUE TITLE
Do you consider joining "thumbor-video-engine"?

### ISSUE THREAD

**Issue by Aunixtoyou** [beeyev/thumbor-s3-docker#18]
The [thumbor-video-engine](https://github.com/theatlantic/thumbor-video-engine) can get video frames，it is very important in 
image preview service

**Comment by beeyev** [comment]
Yes, I can add this library into the container. Will you be able to test it properly if I provide you with a test docker image?

**Comment by Aunixtoyou** [comment]
sorry, I only have linux x86 environment, cant't cover all tests.

**Comment by beeyev** [comment]
I suggest to use this project, to work with video
https://github.com/cshum/imagorvideo

**Comment by Aunixtoyou** [comment]
Thanks!
